### ISSUE TITLE
Scrolling issue when changing leftStickyColumnCount to 1

### ISSUE THREAD

**Issue by nicosmic** [henrybuilt/react-sticky-table#108]
Hello and thank you for this convenient package,

When a stickyHeaderCount is set to 1 or greater and the leftStickyColumnCount is already set to 2 or greater, everything is ok. But then if we change the leftStickyColumnCount to 1, there is a strange behaviour : the headers of the previously sticky columns stay sticky, with the "left" css attribute defined to the previous value.
![react-sticky-table_scroll-issue](https://user-images.githubusercontent.com/25016989/95892234-80a4e100-0d86-11eb-9550-ed68cf423a9f.png)

![react-sticky-table_scroll-issue](https://user-images.githubusercontent.com/25016989/95891555-851cca00-0d85-11eb-86e3-ccb43c607a06.gif)

If there is no sticky header, the "left" css attribute is also present but the "position" attribute is not set to "sticky" so it has no impact.

This issue only appears if stickyHeaderCount is greater than 0 and if we change leftStickyColumnCount dynamically from 2+ to 1.

I tried to debug it but i'm not sure on how to resolve it.

Do you have any workaround or do you intend to fix this issue please ?

Thank you.

**Comment by maxhudson** [comment]
Odd condition you found! We didn't anticipate people dynamically changing that count much so didn't test that, but will look at it. I'm surprised that's an issue as our implementation is pretty "reactive"/should render properly to match updated props

**Comment by maxhudson** [comment]
This is happening for a somewhat subtle reason:

1. an interval to set insets gets set when there is more than one sticky (so, say starting value 2 sticky columns)
2. that interval updates state.stickyInsets which affects css styles
3. if all sticky counts are one, that function will stop running (it'll clear the interval and consider rerunning the interval which it will decide not to do) - the interval would reset the insets to the correct undefined values for the 2nd column, but it's not running so that value isn't being cleared.

state.stickyInsets should be reset whenever the interval is cleared - PR incoming

**Comment by nicosmic** [comment]
Ok great, thank you !

**Comment by maxhudson** [comment]
https://github.com/henrybuilt/react-sticky-table/releases/tag/5.1.10

Tested with storybook and it appears to work!
