### ISSUE TITLE
Responsive Height 

### ISSUE THREAD

**Issue by bflannery** [henrybuilt/react-sticky-table#24]
I've followed your demo and have `width` and `height` set in the `<div>` wrapping the `<StickyTable>` component. I want to make the table responsive and adjust based on the number of rows in the table but can't seem to figure out how to do so. If I change `height` to `auto` or use `maxHeight`, the table loses the sticky headers and now scroll with the rows. 

<img width="370" alt="screen shot 2018-03-30 at 11 28 19 am" src="https://user-images.githubusercontent.com/20323476/38145163-8e4d37c6-340d-11e8-81ae-621801c25173.png">

As you can see here, the blue is the wrapping <div> with height set. I want this to collapse to the height of the rows.

Any thoughts?

**Comment by maxhudson** [comment]
I'm not sure why the headers are wrapping in this case, but if you're setting the `height` or `width` of any `.sticky-table-table` elements, that is probably going to create issues.

It sounds like what you're trying to do is make the table behave like a div with `max-height: X` that shrinks to fit its content if it's content's `height` is less than `X`. Unfortunately I'm not sure there's a way to do that as-is, but that seems useful. Please confirm that is in-fact your issue though.

I'd be happy to accept a pull request with code for this, but it definitely wouldn't be a one-liner and would need some javascript code (I don't think there's a plain CSS fix). In the meantime I'll think about a proper solution and possibly implement one myself.

Since it looks like you only need a sticky header, there's probably a css-only solution for you like so: https://codepen.io/tjvantoll/pen/JEKIu 

The only problem with that is you probably won't get dynamic cell widths.

**Comment by bflannery** [comment]
```it sounds like what you're trying to do is make the table behave like a div with max-height: X that shrinks to fit its content if it's content's height is less than X. Unfortunately I'm not sure there's a way to do that as-is, but that seems useful. Please confirm that is in-fact your issue though.```

This is correct. I figured it wouldn't be that easy as everything I've tried with css so far forces me to give up one functionality for the other. 

I am trying to have both a sticky first column and headers as well.

I haven't played around with your code yet to see if I can provide something worth a PR but will look at it more. I'll keep my eye on the repo to see if you come up with anything on your end.

Thanks!

**Comment by maxhudson** [comment]
@bflannery sounds good. Your dilemma is not uncommon, I'm sure, so it'd be a valuable addition. Feel free to ask questions if you take a swing at it and I'll be sure to let you know if I fix it myself.

**Comment by jacobweber** [comment]
I'm seeing a related issue. If I don't specify a height in the surrounding DIV, then on iOS, the table disappears as soon as you try to scroll it. I'm not using sticky headers or any style overries, just sticky columns.

You can see this if you load the [demo page](https://henrybuilt.github.io/react-sticky-table/#resizing-cells-example) in an iOS simulator (I used an iPhone X sim with iOS 11.3). Inspect the page with Safari and remove the "height: 200px" rule. Then drag on the table to scroll, and it will disappear.

My use case: I want the entire page to scroll vertically, rather than having the table scroll within a DIV in the page. This was possible with 1.2.x; at least, I didn't see this issue with it.

**Comment by maxhudson** [comment]
@jacobweber This is a feature request rather than a bug. Neither version was intended to support that behavior, but I see why it would be important if you wanted just a sticky column. I'll add it to the list.

Do you just have a sticky column showing and no header?

**Comment by jacobweber** [comment]
In my current use case, yeah — just a sticky column with a non-sticky header.

I can also see the need for a case where the table has a flex height, rather than a specific pixel height. In that case I might want a sticky header as well.

**Comment by maxhudson** [comment]
Should be resolved now
