### ISSUE TITLE
Render rows in separate components

### ISSUE THREAD

**Issue by jacobweber** [henrybuilt/react-sticky-table#25]
I'd like to move my rows into separate components. The purpose is to make them pure components, so they don't need to be individually re-rendered if I sort the array of objects that generates them.

So I modified the example on the home page to look like:
```
import React, { Component } from 'react';

import { StickyTable, Row, Cell } from 'react-sticky-table';
import 'react-sticky-table/dist/react-sticky-table.css';

class SampleRow extends Component {
  render() {
    return (
      <Row>
        <Cell>Cell 1</Cell>
        <Cell>Cell 2</Cell>
      </Row>
    );
  }
}

export default class App extends Component {
  render() {
    return (
      <div>
        <div style={{width: '100%', height: '400px'}}>
          <StickyTable>
            <Row>
              <Cell>Header 1</Cell>
              <Cell>Header 2</Cell>
            </Row>
            <SampleRow />
          </StickyTable>
        </div>
      </div>
    );
  }
}
```

But this results in an error:
```
TypeError: Cannot read property 'style' of undefined
(anonymous function)
node_modules/react-sticky-table/dist/index.js:359

  356 | }
  357 | 
  358 | cells.forEach(function (cell) {
> 359 |   return cell.style.height = '';
  360 | });
  361 | 
  362 | columnHeight = Math.max(_this3.getNodeSize(cells[0]).height, _this3.getNodeSize(cells[1]).height);
```

Version 2.0.1.

**Comment by maxhudson** [comment]
@jacobweber this is a bug and needs to be fixed. I'll take a jab at it this weekend.

**Comment by maxhudson** [comment]
@jacobweber @shnider this should be fixed in the most recent version. If you notice anything buggy about it let me know. `componentDidMount`, `componentWillMount`, etc... may not be called consistently.

I do not recommend using your own component for row generation. Subclassing `<Cell>` shouldn't cause any problems, but rendering `<Row>` elements from another component could behave unexpectedly because `<StickyTable>` is breaking the `<Row>`s up into groups of `<Cell>`s (there are four: `corner`, `header`, `column`, and `body`). Each of these groups gets its own `<div>` with `display: table` and then they're all synced up.

**Comment by jacobweber** [comment]
Thanks for the quick fix. But just to clarify, you mean I shouldn't do the thing you fixed? I can understand why, but it's too bad, since it can make sorting much faster. (I tried it earlier with stickyHeaderCount and stickyColumnCount set to 0, which avoided the error).

I wonder if there's some other way to avoid re-rendering everything when you sort the underlying data, without rendering Row from a pure component.

**Comment by maxhudson** [comment]
@jacobweber there's no issue with implementing another component if all it's doing is rendering rows, except maybe a slight performance hit. It's just really tricky to respect the integrity of the custom row component beyond the render method because the row is being split up into two rows when there's a sticky column, so the custom row component shouldn't do anything besides render really. I'm sure there's a better solution, but it has yet to make itself clear.

I'm not sure it's possible to avoid rendering on sort because every row has to be moved around in the dom. Resizing of cells shouldn't be necessary on sort, but may be happening anyway unnecessarily, which might cause a noticeable difference in performance. 

Regardless, I think that issue is unrelated to implementing a separate component for each row, but I could be wrong.

**Comment by jacobweber** [comment]
Gotcha. Yeah, it looks like re-rendering of Cell components is happening whenever you sort. If you run this example, you'll see a "render" line in the console for every cell, every time you click Reverse. But if you change it to a normal HTML table, that won't happen. Might be worth optimizing if it's not too difficult.

```
import React from 'react';
import { StickyTable, Row, Cell } from 'react-sticky-table';

class MyStickyCell extends React.PureComponent {
	render() {
		console.log('render ' + this.props.row.value);
		return (
			<Cell>{this.props.row.value}</Cell>
		);
	}
};

class MyStickyTable extends React.PureComponent {
	render() {
		return (
			<div style={{width: '100%', height: '100px'}}>
				<StickyTable stickyHeaderCount={0} stickyColumnCount={0}>
					<Row>
						<Cell>Header</Cell>
					</Row>
					{this.props.data.map(row => (
						<Row key={row.key}>
							<MyStickyCell row={row} />
						</Row>
					))}
				</StickyTable>
			</div>
		);
	}
}

export default class App extends Component {
	constructor(props) {
		super(props);
		this.state = {
			data: [
				{key: 0, value: 'A'},
				{key: 1, value: 'B'}
			]
		};
	}

	reverseData = () => {
		this.setState(prevState => ({
			data: prevState.data.slice().reverse()
		}));
	};

	render() {
		return (
			<div>
				<MyStickyTable data={this.state.data} />
				<button onClick={this.reverseData}>Reverse</button>
			</div>
		);
	}
}
```

**Comment by maxhudson** [comment]
@jacobweber the solution isn't quite as simple as using html table elements, and we can't do that anyway because they break all kinds of css behavior we rely on. 

I'm not sure a solution is realistic, but if it was it would probably involve some kind of detection to determine the reason the render happened (whether it was sort or not). We'd probably need to implement sorting ourselves for this to work reliably.

Again, this is another issue regardless, so I'll move this discussion to a new issue.
