### ISSUE TITLE
What determines the size of the columns?

### ISSUE THREAD

**Issue by FruitAndAShape** [henrybuilt/react-sticky-table#53]
The cells have a width set on the but how does it calculate them but my table is as thin as possible. How do I make it space it out?

**Comment by maxhudson** [comment]
Hi @FruitAndAShape I'm not quite sure what you're asking. If you can provide a screenshot and explain what the desired outcome is in more detail I might be able to help.

**Comment by FruitAndAShape** [comment]
```
<StickyTable style={{width: '100%'}} stickyHeaderCount={1}>
    {[1, 2, 3, 4, 5, 6, 7, 8, 9].map(s => <Row><Cell>a {s}</Cell><Cell>b {s}</Cell></Row>)}
</StickyTable>
```
<img width="511" alt="screenshot 2019-02-21 at 12 33 17" src="https://user-images.githubusercontent.com/7421691/53169352-e3a39c00-35d4-11e9-8f58-503ad6f8820b.png">

The element highlight shows that the table takes up all available space but the cells are as small as they could be. Also, the header isn't lined up - which is my main aim. :)

**Comment by maxhudson** [comment]
I'm still not 100% sure what your ideal outcome is, but:
- the centering of those header rows is probably caused by other styles in your project - I've never seen that before
- you can at least set a minimum width on the content of each cell (i.e. `<Cell><div style={{minWidth: '10rem'}}>cell content</div></Cell>`

If you're seeking the cells to be width 50%, you can probably apply `width: 50% !important` to the table-cell elements using your stylesheet.

**Comment by FruitAndAShape** [comment]
I set every cell to a percentage and it seems to be working. Another issue is that the scroll bar scrolls all the way to the bottom but it doesn't line up with the bottom of the table.

<img width="106" alt="screenshot 2019-02-21 at 16 01 34" src="https://user-images.githubusercontent.com/7421691/53182824-2889fb80-35f2-11e9-9bd3-c4a726d1ed06.png">

This is fully scrolled but you can see the scroll thing isn't flush against the bottom.

**Comment by maxhudson** [comment]
@FruitAndAShape This is probably a bug. You might be able to fix it by inspecting the styles of the `.y-scrollbar` element and seeing if you can override the height.

It's possible you're overriding the `box-sizing: border-box` on some elements that require it and causing incorrect content height calculation.

**Comment by maxhudson** [comment]
@FruitAndAShape this library really exists to support dynamic column widths and combined sticky headers/columns. If you're using fixed column widths there are many other more lightweight solutions out there.

**Comment by FruitAndAShape** [comment]
A percentage width is dynamic. I've added them because otherwise they columns don't take up all available space.

**Comment by FruitAndAShape** [comment]
Which other solutions would you suggest?

**Comment by maxhudson** [comment]
When I say dynamic, I mean based on the size of the content. 50% can be statically defined at compile time, rather than at runtime.

I wouldn't use a library at all if you just need a sticky header. Just create:
-  a div with `display: table-header-group`
-  a div with `display: table-row-group`, a `max-height` and `overflow: auto`

I'd recommend asking/looking around on stack overflow if that doesn't work for you.

**Comment by FruitAndAShape** [comment]
I couldn't work it out. I created two tables, set the dimensions of the columns on both and set `table-layout: fixed; `. Works ok.
