### ISSUE TITLE
Object Styles

### ISSUE THREAD

**Issue by PaulieScanlon** [henrybuilt/react-sticky-table#76]
Hey! Hows it going? What are your thoughts on using the style object syntax with Styled Components. Would it be of interest if i created a PR with this implemented?

**Comment by maxhudson** [comment]
Hey - can you explain what the difference between that and this PR would be? https://github.com/henrybuilt/react-sticky-table/pull/73

And what the benefit of it would be over this? Can you provide a link to some documentation on "style object syntax"?

**Comment by PaulieScanlon** [comment]
Hey. The style object syntax hasn’t been clearly documented on the Style Components Website. I’ve created a PR which is currently being reviewed: https://github.com/styled-components/styled-components-website/pull/444/files

One big difference is the way to use props or rather, it’s cleaner to de-structure props.

**Comment by maxhudson** [comment]
Looks nice and clean. 

Does it basically make it so that any css property becomes a valid react property that automatically gets mapped to a style prop?

Curious how lines like this would get handled: https://github.com/henrybuilt/react-sticky-table/blob/79f9d9ebfcaa7a7278ed58b305c82d24b33679db/src/index.js#L47

And curious how non-css attributes work. 

Would be happy to review a PR!

Max

**Comment by maxhudson** [comment]
Closing this - will reopen if there's action
