### ISSUE TITLE
colSpan for Cell

### ISSUE THREAD

**Issue by cheesest3ak** [henrybuilt/react-sticky-table#8]
how to have an attribute like colspan for the element cell?

**Comment by maxhudson** [comment]
@cheesest3ak there isn't currently a way to do this since colspan is a feature of `<td>` elements and we use `<div>` elements with `display: table-cell` for a number of reasons. We may be able to build this functionality in eventually though.

For now you may be able to use multiple `<Cell>`s and place some overflowing content inside the first one.

**Comment by maxhudson** [comment]
Unfortunately, since we're not using actual table elements, and instead just table display properties (we're doing this for a number of reasons - table elements are an abomination), this would be very difficult and require a major restructuring that probably would involve CSS grid.

I'm not going to add this to the roadmap for now, but if we ever switch to CSS grid, I'll reopen. Happy to look at PRs for this in the meantime.

https://stackoverflow.com/questions/2403990/html-colspan-in-css
